export const technologyFAQs = {
  python: [
    { question: 'What is Python used for?', answer: 'Python is a high-level, general-purpose programming language used in web development (Django, Flask), data science (NumPy, pandas), artificial intelligence (TensorFlow, PyTorch), automation, scripting, and software development. Its readability and extensive standard library make it one of the most versatile languages.' },
    { question: 'Is Python good for beginners?', answer: 'Yes, Python is widely recommended for beginners due to its clean, readable syntax that resembles plain English. Its indentation-based structure reduces the syntactic overhead, allowing new programmers to focus on logic rather than complex syntax.' },
    { question: 'Python vs JavaScript: which should I learn first?', answer: 'Choose Python if you are interested in data science, AI, backend development, or automation. Choose JavaScript if you want to focus on web development, frontend, or full-stack engineering. Both are excellent first languages with strong job markets.' },
    { question: 'Is Python still relevant in 2026?', answer: 'Yes, Python continues to be one of the most in-demand programming languages, driven by its dominance in AI/ML, data science, and backend development. Its ecosystem of libraries and frameworks is actively maintained and growing.' },
    { question: 'What are the best resources to learn Python?', answer: 'Start with the official Python tutorial at python.org, then explore freeCodeCamp\'s Scientific Computing with Python, Real Python tutorials, and practice on Exercism or HackerRank. For books, "Python Crash Course" by Eric Matthes and "Automate the Boring Stuff" by Al Sweigart are highly recommended.' },
    { question: 'How long does it take to learn Python?', answer: 'Basic proficiency can be achieved in 4–6 weeks with consistent daily practice. Intermediate level (working with libraries, APIs, and databases) typically takes 3–6 months. Mastery for specialized domains like data science or ML takes 1–2 years of focused learning.' },
    { question: 'What companies use Python?', answer: 'Major companies using Python include Google (search infrastructure, YouTube), Facebook (backend services), Netflix (data analysis), Spotify (recommendation engine), Instagram (backend), Dropbox (desktop client), and NASA (scientific computing).' },
    { question: 'Does Python have a future in AI?', answer: 'Python is the primary language for AI and machine learning development. TensorFlow, PyTorch, scikit-learn, and JAX all have Python-first APIs. With the rise of LLMs, RAG systems, and AI agents, Python\'s role in AI continues to expand.' },
  ],
  javascript: [
    { question: 'What is JavaScript used for?', answer: 'JavaScript is used for building interactive websites, web applications, server-side applications (Node.js), mobile apps (React Native), desktop apps (Electron), and increasingly for IoT and game development. It is a core technology of the web alongside HTML and CSS.' },
    { question: 'Is JavaScript easy to learn?', answer: 'JavaScript has a relatively gentle learning curve for basic interactivity, but mastering it requires understanding asynchronous programming, closures, prototypes, and the event loop. Its flexibility means there are many ways to accomplish the same task.' },
    { question: 'JavaScript vs TypeScript: which is better?', answer: 'TypeScript builds on JavaScript by adding static typing. For small projects, JavaScript is faster to start. For large-scale applications, TypeScript provides better tooling, error detection, and maintainability. Many teams start with JavaScript and migrate to TypeScript as projects grow.' },
    { question: 'What is Node.js used for?', answer: 'Node.js allows JavaScript to run on servers, enabling full-stack JavaScript development. It excels at building REST APIs, real-time applications (chat, gaming), microservices, and serverless functions. Its non-blocking I/O model makes it efficient for high-throughput applications.' },
    { question: 'What are the best resources to learn JavaScript?', answer: 'MDN Web Docs provides the definitive JavaScript documentation. "Eloquent JavaScript" by Marijn Haverbeke and "You Don\'t Know JS Yet" by Kyle Simpson are excellent books. Interactive platforms like freeCodeCamp, The Odin Project, and JavaScript.info offer comprehensive learning paths.' },
  ],
  typescript: [
    { question: 'What is TypeScript and why use it?', answer: 'TypeScript is a typed superset of JavaScript that compiles to plain JavaScript. It adds static type checking, interfaces, generics, and advanced tooling support. TypeScript catches type-related errors at compile time, improves code documentation through types, and enables better IDE support with autocompletion and refactoring.' },
    { question: 'Is TypeScript worth learning in 2026?', answer: 'Yes, TypeScript has become the standard for professional JavaScript development. Most major frameworks (React, Angular, Vue, Next.js) have first-class TypeScript support. Job listings increasingly require TypeScript knowledge, and the developer survey consistently ranks it as one of the most loved and wanted languages.' },
    { question: 'TypeScript vs JavaScript: what are the key differences?', answer: 'TypeScript extends JavaScript with static typing, interfaces, enums, generics, decorators, and type inference. JavaScript is dynamically typed and runs directly in browsers/Node.js. TypeScript requires a compilation step but catches bugs early and scales better for large codebases.' },
    { question: 'How do I migrate from JavaScript to TypeScript?', answer: 'Start by renaming .js files to .ts and enabling strict mode. Add type annotations incrementally, beginning with function parameters and return types. Use // @ts-check in JavaScript files for gradual migration. The TypeScript handbook provides a comprehensive migration guide from JavaScript.' },
  ],
  java: [
    { question: 'What is Java used for?', answer: 'Java is used for enterprise backend development, Android applications, big data processing (Hadoop, Spark), cloud microservices, and large-scale financial systems. Its platform independence via the JVM makes it ideal for cross-platform enterprise applications.' },
    { question: 'Is Java still relevant in 2026?', answer: 'Absolutely. Java remains one of the most widely used programming languages, powering millions of enterprise applications, Android apps, and cloud-native services. With frequent releases (every 6 months) and features like virtual threads (Project Loom), pattern matching, and records, Java continues to modernize.' },
    { question: 'Java vs Python: which is better for career?', answer: 'Java dominates enterprise backend and Android development with higher average salaries. Python leads in data science and AI. Both have excellent job markets. Java offers stability in large organizations, while Python offers growth in emerging tech fields.' },
    { question: 'How long does it take to learn Java?', answer: 'Basic Java proficiency takes 2–3 months with daily practice. Intermediate level (Spring Boot, databases, REST APIs) takes 6–12 months. Professional mastery with enterprise patterns and JVM internals takes 2+ years.' },
    { question: 'What are the best Java learning resources?', answer: 'Oracle\'s official Java tutorials, Baeldung for Spring content, and "Effective Java" by Joshua Bloch are essential. "Head First Java" is excellent for beginners. Practice on HackerRank and LeetCode. The Spring Boot reference documentation is the definitive guide for modern Java web development.' },
  ],
  go: [
    { question: 'What is Go used for?', answer: 'Go is used for cloud-native services, microservices, CLI tools, DevOps infrastructure, networking applications, and concurrent systems. It powers Docker, Kubernetes, Prometheus, Terraform, and many cloud infrastructure tools.' },
    { question: 'Is Go worth learning?', answer: 'Yes, Go is highly valued in cloud infrastructure, DevOps, and backend engineering. It offers simplicity, fast compilation, built-in concurrency, and excellent performance. Go developers are in high demand for cloud-native and infrastructure roles.' },
    { question: 'Go vs Rust: which should I learn?', answer: 'Choose Go for web services, microservices, cloud infrastructure, and CLI tools where development speed and simplicity matter. Choose Rust for systems programming, embedded development, WebAssembly, and scenarios requiring maximum performance and memory safety without garbage collection.' },
    { question: 'What companies use Go?', answer: 'Google (core infrastructure), Docker, Kubernetes, Netflix, Uber, Twitch, Dropbox, Cloudflare, and many cloud-native companies rely on Go for performance-critical backend services and infrastructure tooling.' },
  ],
  rust: [
    { question: 'What is Rust used for?', answer: 'Rust is used for systems programming, game engines, WebAssembly, embedded systems, CLI tools, networking services, and performance-critical applications. It offers memory safety without garbage collection, making it ideal for reliable low-level software.' },
    { question: 'Is Rust difficult to learn?', answer: 'Rust has a steep learning curve due to its ownership model, borrowing rules, and lifetimes. However, once mastered, these concepts eliminate entire categories of bugs. Expect 3–6 months for basic proficiency and 12+ months for advanced understanding.' },
    { question: 'What companies use Rust?', answer: 'Mozilla (Firefox), Microsoft (Windows kernel components), Google (Android, Fuchsia), Amazon (AWS infrastructure), Cloudflare (edge services), Figma (performance-critical rendering), and Dropbox (file synchronization engine).' },
    { question: 'Is Rust worth learning in 2026?', answer: 'Absolutely. Rust has been voted the most loved language in Stack Overflow surveys for years. With growing adoption in Linux kernel, WebAssembly, cloud infrastructure, and security-critical applications, Rust skills are increasingly valuable.' },
  ],
  cpp: [
    { question: 'What is C++ used for?', answer: 'C++ is used for game development (Unreal Engine), high-frequency trading, embedded systems, operating systems, database engines, browsers (Chrome, Firefox), and performance-critical applications where hardware-level control is needed.' },
    { question: 'Is C++ still relevant?', answer: 'Yes, C++ remains essential for performance-critical domains: game engines, trading systems, embedded software, and large-scale infrastructure. Modern C++ (C++17/20/23) adds significant improvements making it safer and more productive.' },
    { question: 'C++ vs Rust: which is better for systems programming?', answer: 'C++ offers mature tooling, vast libraries, and deep industry adoption. Rust offers memory safety guarantees without garbage collection. For new systems projects, Rust is increasingly preferred. For existing codebases and game development, C++ dominates.' },
  ],
  csharp: [
    { question: 'What is C# used for?', answer: 'C# is used for Windows desktop applications, game development (Unity), enterprise web applications (ASP.NET Core), cloud services (Azure), mobile apps (Xamarin/MAUI), and cross-platform development with .NET.' },
    { question: 'Is C# good for game development?', answer: 'Yes, C# is the primary language for Unity, the most popular game engine for indie and mobile games. It also works with MonoGame and Stride. Its garbage collection and extensive framework make it productive for game prototyping and production.' },
    { question: 'C# vs Java: what are the differences?', answer: 'Both are object-oriented, statically typed, and JVM/CLR-based. C# has better language innovation (LINQ, async/await, records, pattern matching), deeper Windows integration, and Unity game development. Java has larger enterprise ecosystem and Android development.' },
  ],
  php: [
    { question: 'What is PHP used for?', answer: 'PHP powers most content management systems (WordPress, Drupal, Joomla), e-commerce platforms (WooCommerce, Magento), and web frameworks (Laravel, Symfony). It runs over 75% of websites whose server-side language is known.' },
    { question: 'Is PHP still relevant in 2026?', answer: 'Yes, PHP 8.x brings significant performance and language improvements including JIT compilation, attributes, enums, and named arguments. Laravel and Symfony are modern, well-architected frameworks. PHP remains dominant for CMS-driven websites and has strong job demand.' },
    { question: 'Laravel vs Symfony: which PHP framework should I learn?', answer: 'Laravel offers easier onboarding, convention-over-configuration, and an extensive ecosystem (Forge, Vapor, Nova). Symfony provides more flexibility, reusable components, and is better suited for complex enterprise applications. Both are excellent choices.' },
  ],
  kotlin: [
    { question: 'What is Kotlin used for?', answer: 'Kotlin is the official language for Android development, and is also used for backend development (Ktor, Spring Boot), multiplatform mobile apps (Kotlin Multiplatform), and data science. It offers full Java interop with more concise, safer syntax.' },
    { question: 'Kotlin vs Java: which to choose for Android?', answer: 'Kotlin is the recommended language for Android development by Google. It offers null safety, coroutines, extension functions, and data classes that reduce boilerplate. However, existing Android codebases often mix both languages during migration.' },
    { question: 'Is Kotlin good for backend development?', answer: 'Yes, Kotlin works excellently with Spring Boot and has dedicated frameworks like Ktor. Its coroutines provide efficient asynchronous programming. Kotlin Multiplatform enables sharing business logic across Android, iOS, web, and backend.' },
  ],
  swift: [
    { question: 'What is Swift used for?', answer: 'Swift is used for iOS, iPadOS, macOS, tvOS, and watchOS application development. It is Apple\'s modern replacement for Objective-C and is used for all native Apple platform development.' },
    { question: 'Is Swift only for Apple development?', answer: 'Primarily yes, though Swift has expanded to server-side (Vapor, Kitura) and even Android (Swift Android Toolchain). Its main use case remains Apple ecosystem development.' },
    { question: 'Swift vs Objective-C: which to learn?', answer: 'Swift is the modern choice for all new Apple platform development. It offers better performance, safety, and modern language features. Learn SwiftUI for new apps and UIKit for maintaining legacy apps.' },
  ],
  react: [
    { question: 'What is React used for?', answer: 'React is a JavaScript library for building user interfaces, particularly single-page applications. It is used for web applications, mobile apps (React Native), and with frameworks like Next.js for full-stack and static site generation.' },
    { question: 'React vs Vue vs Angular: which is best?', answer: 'React offers the largest ecosystem, most job opportunities, and greatest flexibility. Vue provides gentler learning curve and excellent documentation. Angular offers a complete framework with strong typing and enterprise patterns. Choose based on team expertise and project requirements.' },
    { question: 'Is React still relevant with new frameworks?', answer: 'Yes, React remains the most popular frontend library. With features like server components, Suspense, and the new compiler, React continues to evolve. Next.js, built on React, is the leading framework for production React applications.' },
  ],
  nodejs: [
    { question: 'What is Node.js used for?', answer: 'Node.js enables JavaScript server-side development. It is used for REST APIs, real-time applications, microservices, serverless functions, CLI tools, and build tooling. Its event-driven, non-blocking architecture excels at I/O-intensive applications.' },
    { question: 'Is Node.js good for backend development?', answer: 'Yes, Node.js is excellent for building scalable network applications, REST APIs, and real-time services. Its npm ecosystem provides over 2 million packages. Frameworks like Express, Fastify, and NestJS provide structured development patterns.' },
    { question: 'Node.js vs Deno vs Bun: which runtime to choose?', answer: 'Node.js has the largest ecosystem and broadest production adoption. Deno offers better security defaults, TypeScript natively, and modern APIs. Bun provides blazing-fast startup and is compatible with Node.js APIs. For production, Node.js remains the safest choice.' },
  ],
  docker: [
    { question: 'What is Docker used for?', answer: 'Docker containerizes applications so they run consistently across any environment. It packages software with all dependencies into standardized units called containers, solving "it works on my machine" problems and streamlining deployment.' },
    { question: 'Docker vs Virtual Machines: what is the difference?', answer: 'Docker containers share the host OS kernel and start in seconds using megabytes of storage. Virtual machines include a full guest OS, taking minutes to start and gigabytes of storage. Containers are ideal for microservices, while VMs provide stronger isolation.' },
    { question: 'Do I need Docker as a developer?', answer: 'Yes, Docker has become essential for modern development. It ensures consistent environments across team members, simplifies CI/CD pipelines, and is the foundation of Kubernetes and cloud-native deployments.' },
  ],
  kubernetes: [
    { question: 'What is Kubernetes used for?', answer: 'Kubernetes orchestrates containerized applications across clusters of machines. It handles deployment, scaling, load balancing, service discovery, rolling updates, and self-healing of containerized workloads.' },
    { question: 'Is Kubernetes hard to learn?', answer: 'Kubernetes has a steep learning curve due to its complex architecture of control plane components, node components, and numerous resource types. Expect 2–4 months to achieve production-level competency.' },
    { question: 'Kubernetes vs Docker Swarm: which is better?', answer: 'Kubernetes offers richer features, broader ecosystem, and industry-wide adoption. Docker Swarm provides simpler setup and is easier to learn. For production at scale, Kubernetes is the standard choice.' },
  ],
  aws: [
    { question: 'What is AWS used for?', answer: 'AWS provides cloud computing services including compute (EC2, Lambda), storage (S3), databases (RDS, DynamoDB), AI/ML (SageMaker), and over 200 services. It is the largest cloud platform powering millions of applications worldwide.' },
    { question: 'Which AWS certification should I get first?', answer: 'Start with AWS Certified Cloud Practitioner for foundational knowledge, then pursue AWS Certified Solutions Architect – Associate for architecture skills, or AWS Certified Developer – Associate for development-focused roles.' },
    { question: 'Is AWS worth learning?', answer: 'AWS skills are among the most valuable in cloud computing. With 30%+ market share and deep enterprise adoption, AWS knowledge translates to strong career opportunities and higher salaries.' },
  ],
  azure: [
    { question: 'What is Azure used for?', answer: 'Azure is Microsoft\'s cloud platform offering compute, storage, AI, analytics, and DevOps services. It excels in hybrid cloud, enterprise integration with Microsoft products, and .NET application hosting.' },
    { question: 'Azure vs AWS: which is better?', answer: 'AWS offers more services and broader global infrastructure. Azure provides better integration with Microsoft enterprise tools (Active Directory, Office 365, SQL Server). Choose based on your organization\'s technology stack and requirements.' },
    { question: 'Which Azure certification should I pursue?', answer: 'Start with Azure Fundamentals (AZ-900), then specialize based on your role: Azure Developer Associate (AZ-204), Azure Solutions Architect (AZ-305), or Azure DevOps Engineer Expert (AZ-400).' },
  ],
  tensorflow: [
    { question: 'What is TensorFlow used for?', answer: 'TensorFlow is used for building and deploying machine learning models, particularly deep learning for image recognition, natural language processing, recommendation systems, and predictive analytics.' },
    { question: 'TensorFlow vs PyTorch: which should I learn?', answer: 'PyTorch has become the dominant framework for research due to its Pythonic, dynamic nature and easier debugging. TensorFlow excels in production deployment with TensorFlow Serving, Lite, and JS. Many practitioners learn both.' },
    { question: 'Is TensorFlow still relevant?', answer: 'Yes, TensorFlow is widely used in production ML systems, mobile/edge ML (TensorFlow Lite), and web ML (TensorFlow.js). Keras, now part of TensorFlow, provides a high-level API that simplifies model building.' },
  ],
  pytorch: [
    { question: 'What is PyTorch used for?', answer: 'PyTorch is used for deep learning research and production, powering large language models, computer vision, and reinforcement learning. It is the most popular framework for AI research and development.' },
    { question: 'Why is PyTorch popular for research?', answer: 'PyTorch\'s dynamic computation graph, Pythonic debugging, and eager execution mode make it intuitive for research. Its flexibility allows easy experimentation, and it has become the standard framework for academic papers and AI courses.' },
    { question: 'How do I get started with PyTorch?', answer: 'Start with the official PyTorch tutorials, then take fast.ai\'s Practical Deep Learning course. DeepLearning.AI\'s PyTorch specialization provides structured learning. Practice by implementing classic architectures on Kaggle datasets.' },
  ],
  mongodb: [
    { question: 'What is MongoDB used for?', answer: 'MongoDB is a NoSQL document database used for applications requiring flexible schemas, horizontal scaling, and rapid iteration. It is popular in web applications, real-time analytics, content management, and IoT applications.' },
    { question: 'MongoDB vs PostgreSQL: which to choose?', answer: 'Choose MongoDB when you need flexible schemas, rapid development, and horizontal scaling. Choose PostgreSQL for complex queries, strong consistency, and relational data with joins. Many modern applications use both for different workloads.' },
    { question: 'Is MongoDB good for production?', answer: 'Yes, MongoDB is production-proven at scale by companies like Adobe, eBay, LinkedIn, and Uber. With replica sets and sharding, it provides high availability and horizontal scaling. MongoDB Atlas provides managed cloud deployments.' },
  ],
  postgresql: [
    { question: 'What is PostgreSQL used for?', answer: 'PostgreSQL is an advanced open-source relational database used for web applications, data warehousing, geospatial applications (PostGIS), and as a general-purpose OLTP database. It supports ACID transactions, JSON, full-text search, and custom extensions.' },
    { question: 'Why is PostgreSQL so popular?', answer: 'PostgreSQL offers the best combination of reliability, features, and performance among open-source databases. It supports advanced SQL features, extensibility through extensions, strong ACID compliance, and has excellent community support.' },
    { question: 'PostgreSQL vs MySQL: which is better?', answer: 'PostgreSQL offers more advanced features (CTEs, window functions, custom types, full-text search), better standards compliance, and stronger concurrency control. MySQL offers simpler replication, broader hosting support, and is easier to administer in basic use cases.' },
  ],
  redis: [
    { question: 'What is Redis used for?', answer: 'Redis is an in-memory data structure store used for caching, session management, real-time analytics, message queues, rate limiting, and as a primary database for high-throughput applications requiring sub-millisecond latency.' },
    { question: 'When should I use Redis?', answer: 'Use Redis for caching frequently accessed data, storing user sessions, implementing rate limiting, building real-time leaderboards, managing job queues, and any workload requiring extremely fast data access with optional persistence.' },
    { question: 'Is Redis a database or a cache?', answer: 'Redis is both. It functions as a high-speed in-memory cache with optional persistence to disk, making it a primary database for certain workloads. Redis Stack adds document storage, search, and time series capabilities.' },
  ],
  linux: [
    { question: 'What is Linux used for?', answer: 'Linux is the dominant operating system for servers, cloud infrastructure, embedded systems, Android, supercomputers, and development environments. It powers the majority of the internet, cloud platforms, and enterprise infrastructure.' },
    { question: 'Why should developers learn Linux?', answer: 'Linux is essential for backend development, DevOps, cloud computing, and any server-side work. Understanding the Linux command line, file system, process management, and shell scripting is fundamental for professional software development.' },
    { question: 'Which Linux distribution should I use?', answer: 'Ubuntu is the most popular for beginners and general development. Debian is stable and widely used on servers. Fedora offers cutting-edge packages. Alpine is minimal for containers. Choose based on your specific needs and community support.' },
  ],
  nginx: [
    { question: 'What is Nginx used for?', answer: 'Nginx is a high-performance web server, reverse proxy, load balancer, and HTTP cache. It is used to serve static content, proxy requests to application servers, terminate SSL/TLS, and distribute traffic across multiple servers.' },
    { question: 'Nginx vs Apache: which is better?', answer: 'Nginx offers better performance under high concurrency with event-driven architecture and lower memory usage. Apache provides easier configuration with .htaccess files and broader module support. Nginx is preferred for modern high-traffic web applications.' },
    { question: 'Is Nginx difficult to configure?', answer: 'Nginx configuration is straightforward once you understand its directive-based syntax. Key concepts include server blocks (virtual hosts), location blocks for URL routing, and upstream blocks for load balancing. The official documentation provides clear examples.' },
  ],
  ai: [
    { question: 'What is Artificial Intelligence?', answer: 'Artificial Intelligence is the field of computer science focused on creating systems capable of performing tasks that typically require human intelligence, including learning, reasoning, problem-solving, perception, and language understanding.' },
    { question: 'What is the difference between AI, ML, and DL?', answer: 'AI is the broad field of intelligent systems. Machine Learning is a subset where systems learn from data. Deep Learning is a subset of ML using neural networks with multiple layers. Deep Learning powers most modern AI breakthroughs like LLMs and computer vision.' },
    { question: 'How do I start learning AI?', answer: 'Begin with Python programming, then study mathematics foundations (linear algebra, calculus, probability). Take Andrew Ng\'s Machine Learning course on Coursera, then explore DeepLearning.AI\'s specializations. Practice on Kaggle and contribute to open-source AI projects.' },
  ],
  ml: [
    { question: 'What is Machine Learning?', answer: 'Machine Learning is a subset of AI where algorithms learn patterns from data without explicit programming. It spans supervised learning (classification, regression), unsupervised learning (clustering), and reinforcement learning (agent-based decision making).' },
    { question: 'What are the prerequisites for Machine Learning?', answer: 'Core prerequisites include Python programming, linear algebra, calculus, probability and statistics, and data manipulation skills. Understanding of basic algorithms and data structures is helpful but not required to start.' },
    { question: 'Which Machine Learning library should I learn first?', answer: 'Start with scikit-learn for classical ML algorithms (regression, classification, clustering). Its consistent API and excellent documentation make it ideal for beginners. Then progress to TensorFlow or PyTorch for deep learning.' },
  ],
  cybersecurity: [
    { question: 'What is cybersecurity?', answer: 'Cybersecurity involves protecting systems, networks, and data from digital attacks. It encompasses network security, application security, information security, incident response, and compliance. It is critical for protecting sensitive data and maintaining trust.' },
    { question: 'How do I start a career in cybersecurity?', answer: 'Begin with networking and OS fundamentals. Study the OWASP Top 10 for web security. Earn foundational certifications like CompTIA Security+. Practice on platforms like TryHackMe and Hack The Box. Specialize in areas like penetration testing, security engineering, or incident response.' },
    { question: 'What are the best cybersecurity certifications?', answer: 'Entry-level: CompTIA Security+. Intermediate: CEH, GIAC GPEN. Advanced: OSCP, CISSP. Cloud security: CCSP. Choose based on your career path: offensive security (OSCP, GPEN), defensive (GCIH, CISSP), or governance (CISSP, CISM).' },
  ],
  android: [
    { question: 'What is Android development?', answer: 'Android development involves creating applications for the Android operating system using Kotlin or Java. It covers UI design with Jetpack Compose or XML layouts, app architecture, API integration, and Google Play Store deployment.' },
    { question: 'Should I learn Kotlin or Java for Android?', answer: 'Kotlin is the officially recommended language for Android development. It offers null safety, coroutines, extension functions, and modern syntax. Java remains relevant for maintaining existing codebases but Kotlin is preferred for new projects.' },
    { question: 'Is Android development still a good career?', answer: 'Yes, Android has over 3 billion active devices worldwide. Android developers are in high demand with competitive salaries. The rise of foldables, tablets, Android TV, and Wear OS creates additional opportunities beyond phone apps.' },
  ],
  flutter: [
    { question: 'What is Flutter used for?', answer: 'Flutter is Google\'s UI toolkit for building natively compiled applications for mobile (iOS, Android), web, desktop (Windows, macOS, Linux), and embedded devices from a single codebase using the Dart language.' },
    { question: 'Flutter vs React Native: which is better?', answer: 'Flutter offers better performance through its own rendering engine, consistent UI across platforms, and faster compilation (hot reload). React Native uses native components and has a larger ecosystem. Both are excellent for cross-platform development.' },
    { question: 'Is Flutter good for production apps?', answer: 'Yes, Flutter powers production apps from Google (Google Pay), Alibaba (Xianyu), Tencent, BMW, and many others. It provides excellent performance, customizable widgets, and strong tooling support.' },
  ],
  html: [
    { question: 'What is HTML?', answer: 'HTML (HyperText Markup Language) is the standard markup language for creating web pages and web applications. It provides the structure and content of a web page using elements like headings, paragraphs, links, images, and forms.' },
    { question: 'Is HTML a programming language?', answer: 'HTML is a markup language, not a programming language, because it describes structure and content rather than implementing logic. It is always used alongside CSS for styling and JavaScript for interactivity.' },
    { question: 'What is HTML5?', answer: 'HTML5 is the latest major version of HTML, introducing semantic elements (header, nav, article, section), multimedia support (video, audio without plugins), canvas for graphics, form enhancements, and APIs for offline storage, geolocation, and more.' },
  ],
  css: [
    { question: 'What is CSS used for?', answer: 'CSS (Cascading Style Sheets) controls the visual presentation of HTML elements including layout, colors, fonts, animations, and responsive design. It separates content from presentation, enabling consistent styling across web pages.' },
    { question: 'What is the difference between CSS Grid and Flexbox?', answer: 'Flexbox is ideal for one-dimensional layouts (rows or columns) and distributing space along a single axis. CSS Grid is designed for two-dimensional layouts with precise control over rows and columns. Modern layouts often combine both.' },
    { question: 'Should I learn Tailwind CSS?', answer: 'Tailwind CSS is a utility-first framework that provides low-level utility classes for rapid custom designs without writing custom CSS. It is excellent for productivity and consistency, though it requires learning its class naming system.' },
  ],
  vue: [
    { question: 'What is Vue.js used for?', answer: 'Vue.js is a progressive JavaScript framework for building user interfaces and single-page applications. It is known for its gentle learning curve, reactive data binding, component-based architecture, and excellent documentation.' },
    { question: 'Vue vs React: which is easier to learn?', answer: 'Vue has a gentler learning curve with its single-file components, template syntax similar to HTML, and clear separation of concerns. React requires understanding JSX, hooks, and state management patterns. Both are excellent choices for modern web development.' },
    { question: 'Is Vue.js good for large applications?', answer: 'Yes, Vue.js scales well with its ecosystem (Vue Router, Pinia, Nuxt.js). Large companies like GitLab, Alibaba, Xiaomi, and Nintendo use Vue.js in production. Composition API and TypeScript support make Vue suitable for enterprise applications.' },
  ],
  angular: [
    { question: 'What is Angular used for?', answer: 'Angular is a TypeScript-based web application framework for building large-scale, enterprise single-page applications. It provides a complete solution with routing, forms, HTTP client, dependency injection, and testing utilities.' },
    { question: 'Angular vs React: which is better for enterprise?', answer: 'Angular provides a complete, opinionated framework with built-in solutions for common enterprise needs. React offers more flexibility but requires choosing from many third-party libraries. Angular is often preferred for large team projects requiring standardized architecture.' },
    { question: 'Is Angular still relevant?', answer: 'Yes, Angular is widely used in enterprise environments, particularly in finance, healthcare, and government sectors. With standalone components, signals, and improved developer experience, Angular continues to evolve and remain competitive.' },
  ],
  nextjs: [
    { question: 'What is Next.js used for?', answer: 'Next.js is a React framework for production applications. It provides server-side rendering, static site generation, API routes, file-based routing, image optimization, and middleware. It is used for marketing sites, e-commerce, dashboards, and full-stack web applications.' },
    { question: 'Next.js vs plain React: which should I use?', answer: 'Use Next.js for projects requiring SEO, server-side rendering, static generation, or full-stack capabilities. Use plain React for simple SPAs, interactive widgets embedded in existing pages, or when you need minimal overhead.' },
    { question: 'Is Next.js good for SEO?', answer: 'Yes, Next.js is excellent for SEO. Its server-side rendering and static generation provide fully rendered HTML to search engines. Built-in metadata API, dynamic OG images, and sitemap generation make it a top choice for SEO-optimized web applications.' },
  ],
  express: [
    { question: 'What is Express.js used for?', answer: 'Express.js is a minimal and flexible Node.js web application framework providing a robust set of features for building web and mobile applications, REST APIs, and server-side middleware.' },
    { question: 'Is Express.js still relevant?', answer: 'Yes, Express.js remains the most popular Node.js web framework with the largest ecosystem. Its minimalist design makes it the foundation for many higher-level frameworks (NestJS, Fastify alternatives). While newer options exist, Express\'s maturity and community support are unmatched.' },
    { question: 'Express vs Fastify: which is better?', answer: 'Fastify offers better performance and built-in schema validation. Express has larger community, more middleware, and broader ecosystem. For high-performance APIs, Fastify is compelling. For general web development, Express\'s maturity and resources make it a safe choice.' },
  ],
  springboot: [
    { question: 'What is Spring Boot used for?', answer: 'Spring Boot is a Java-based framework for building stand-alone, production-grade Spring applications with minimal configuration. It simplifies microservices development, REST API creation, database access, and enterprise application development.' },
    { question: 'Is Spring Boot good for microservices?', answer: 'Yes, Spring Boot is excellent for microservices with embedded servers, distributed configuration, service discovery (Eureka), circuit breakers (Resilience4J), API gateways (Spring Cloud Gateway), and distributed tracing (Spring Cloud Sleuth).' },
    { question: 'Do I need to learn Spring before Spring Boot?', answer: 'Spring Boot is designed to start with minimal Spring knowledge. It auto-configures many components and provides sensible defaults. However, understanding Spring fundamentals (dependency injection, IoC, AOP) becomes important for complex scenarios.' },
  ],
  django: [
    { question: 'What is Django used for?', answer: 'Django is a high-level Python web framework for building secure, scalable, and database-driven web applications. It follows the "batteries-included" philosophy with built-in admin, ORM, authentication, and templating.' },
    { question: 'Django vs Flask: which should I learn?', answer: 'Django provides more built-in features (admin, ORM, auth) and is better for larger applications. Flask offers minimalism and flexibility for smaller projects or microservices. Both are excellent choices for Python web development.' },
    { question: 'Is Django good for production?', answer: 'Yes, Django powers production applications for Instagram, Pinterest, Mozilla, Spotify, and The Washington Post. Its security features, scalability, and extensive ecosystem make it one of the most proven Python web frameworks.' },
  ],
  flask: [
    { question: 'What is Flask used for?', answer: 'Flask is a lightweight Python web framework used for building web applications, REST APIs, and microservices. Its minimal design gives developers flexibility to choose their components while providing essentials for routing and request handling.' },
    { question: 'Flask vs FastAPI: which is better for APIs?', answer: 'FastAPI offers automatic OpenAPI documentation, request validation, async support, and better performance. Flask has larger ecosystem and simpler learning curve. FastAPI is recommended for new API projects, Flask for general web applications.' },
    { question: 'When should I use Flask instead of Django?', answer: 'Use Flask for microservices, simple APIs, projects where you want minimal overhead, or when you need flexibility to choose individual components. Flask\'s extension system lets you add only what you need.' },
  ],
  laravel: [
    { question: 'What is Laravel used for?', answer: 'Laravel is a PHP web framework for building full-stack web applications following the MVC pattern. It provides elegant syntax, Eloquent ORM, Blade templating, artisan CLI, and a rich ecosystem including Forge, Vapor, Nova, and Cashier.' },
    { question: 'Why is Laravel so popular?', answer: 'Laravel\'s popularity comes from its elegant syntax, extensive documentation, vibrant community, and comprehensive ecosystem. Features like Eloquent ORM, Blade templating, artisan CLI, and built-in authentication make development fast and enjoyable.' },
    { question: 'Is Laravel good for large applications?', answer: 'Yes, Laravel scales well with features like queues for heavy processing, caching (Redis/Memcached), horizontal scaling support, and modular package architecture. Many large platforms use Laravel in production.' },
  ],
  dotnet: [
    { question: 'What is ASP.NET Core used for?', answer: 'ASP.NET Core is a cross-platform, high-performance framework for building modern, cloud-enabled web applications, REST APIs, and microservices with .NET. It provides built-in dependency injection, middleware pipeline, and authentication.' },
    { question: 'Is .NET good for web development?', answer: 'Yes, .NET is excellent for web development with ASP.NET Core, Blazor for full-stack C# web apps, and strong tooling support. It offers top-tier performance, enterprise-grade security, and seamless Azure integration.' },
    { question: '.NET Framework vs .NET Core: what is the difference?', answer: '.NET Core (now .NET 5+) is cross-platform, open-source, and designed for modern cloud and microservices applications. .NET Framework is Windows-only and legacy. All new development should target .NET 8+.' },
  ],
  mysql: [
    { question: 'What is MySQL used for?', answer: 'MySQL is the world\'s most popular open-source relational database, used for web applications, e-commerce platforms, content management systems (WordPress, Drupal), and data warehousing.' },
    { question: 'MySQL vs MariaDB: what are the differences?', answer: 'MariaDB is a fork of MySQL by the original MySQL developers, offering additional storage engines, better performance optimizations, and enhanced features. MySQL has broader hosting support and Oracle-backed development. Both are compatible.' },
    { question: 'Is MySQL still relevant in 2026?', answer: 'Yes, MySQL remains the most popular open-source database, powering the majority of web applications. With improvements in JSON support, performance schemas, and group replication, MySQL continues to evolve for modern workloads.' },
  ],
  sqlite: [
    { question: 'What is SQLite used for?', answer: 'SQLite is a self-contained, serverless, zero-configuration SQL database engine used in mobile apps, desktop applications, embedded systems, and development environments. It stores the entire database in a single file.' },
    { question: 'When should I use SQLite vs PostgreSQL?', answer: 'Use SQLite for embedded applications, mobile apps, client-side storage, development/testing, and low-traffic websites. Use PostgreSQL for high-concurrency, multi-user applications requiring network access, advanced features, and production scalability.' },
    { question: 'Is SQLite production-ready?', answer: 'Yes, SQLite is used in billions of devices (every Android and iOS device), in popular applications (Firefox, Chrome, Dropbox), and in embedded systems. It is production-proven for workloads with moderate write concurrency.' },
  ],
  firebase: [
    { question: 'What is Firebase used for?', answer: 'Firebase is Google\'s app development platform providing backend services including real-time database, authentication, cloud functions, hosting, and analytics. It enables rapid development without managing server infrastructure.' },
    { question: 'Firebase vs custom backend: which is better?', answer: 'Firebase accelerates development for MVPs and apps with standard patterns (auth, real-time sync, push notifications). Custom backends offer more flexibility, control, and cost predictability at scale. Many apps start with Firebase and migrate to custom when needed.' },
    { question: 'Is Firebase scalable?', answer: 'Yes, Firebase scales automatically for most applications. Firestore handles millions of concurrent connections. However, costs can grow significantly at scale, and complex queries have limitations compared to SQL databases.' },
  ],
  cassandra: [
    { question: 'What is Cassandra used for?', answer: 'Apache Cassandra is a distributed NoSQL database designed for handling large amounts of data across many commodity servers with high availability and no single point of failure. It powers applications requiring always-on availability and horizontal scalability.' },
    { question: 'Cassandra vs MongoDB: which to choose?', answer: 'Cassandra offers better write performance, linear scalability, and multi-data center replication. MongoDB offers richer query capabilities, flexible document model, and easier operational management. Choose Cassandra for time-series data and high-write workloads.' },
    { question: 'When should I use Cassandra?', answer: 'Use Cassandra when you need high write throughput, linear scalability, multi-region deployment, or always-on availability. It is commonly used for IoT data ingestion, time-series data, recommendation engines, and operational analytics.' },
  ],
  python: null,
  java: null,
  go: null,
  rust: null,
  cpp: null,
  csharp: null,
  php: null,
  javascript: null,
  typescript: null,
  kotlin: null,
  swift: null,
  python: null,
}
